version: '3'

networks:
  task-manager-network:
    driver: bridge
    ipam:
      driver: default

services:
  task-manager-nginx:
    container_name: task-manager-nginx
    image: nginx
    ports:
      - '8000:80'
    links:
      - task-manager-php
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/access.log:/var/log/nginx/access.log
      - ./docker/logs/error.log:/var/log/nginx/error.log
    networks:
      - task-manager-network

  task-manager-php:
    container_name: task-manager-php
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: task-manager-php
    image: task-manager/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
    networks:
      - task-manager-network

  task-manager-mysql:
    container_name: task-manager-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST="%""
      - MYSQL_DATABASE=task_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    networks:
      - task-manager-network

  task-manager-nodejs:
    container_name: task-manager-nodejs
    build:
      context: .
      dockerfile: docker/nodejs.Dockerfile
    container_name: task-manager-nodejs
    image: task-manager/nodejs
    command: bash -c "npm install && npm run watch"
    volumes:
      - ./:/var/www
    networks:
      - task-manager-network
